spring:
  application:
    name: clean-architecture
  data:
    mongodb:
      uri: mongodb://localhost:27017/clean-architecture

jfb:
  client:
    address:
      url: http://localhost:8082/addresses